language: go
sudo: false

go:
  - 1.9
  - tip

services:
  - mongodb

env:
  global:
    - MONGODB_TEST_CXN=localhost
  matrix:
    - FIX_TEST=
    - FIX_TEST=fix40
    - FIX_TEST=fix41
    - FIX_TEST=fix42
    - FIX_TEST=fix43
    - FIX_TEST=fix44
    - FIX_TEST=fix50
    - FIX_TEST=fix50sp1
    - FIX_TEST=fix50sp2

matrix:
  allow_failures:
    - go: tip

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script: make generate; if [ -z "$FIX_TEST" ]; then make build; make; else make build_accept; make $FIX_TEST; fi
